application: adversary-lab
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /css/(.+)
  static_files: static/css/\1
  upload: static/css

- url: /js/(.+)
  static_files: static/js/\1
  upload: static/js

- url: /images/(.+)
  static_files: static/images/\1
  upload: static/images

- url: .*
  script: web.app

libraries:
- name: webapp2
  version: "2.5.2"

builtins:
- deferred: on
- appstats: on
